export const GET_STANDART_EVENTS = 'events.GET_STANDART_EVENTS'
export const GET_STANDART_EVENTS_SUCCESS = 'events.GET_STANDART_EVENTS_SUCCESS'
export const GET_STANDART_EVENTS_ERROR = 'events.GET_STANDART_EVENTS_ERROR'
